title: OP13.dev
author: 
  name: email
  email: will@op13.dev
description: >-
  Notes on tech, DevOps, and other related musings.
baseurl: ""
url: "https://op13.dev"
# Build settings
#theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/william-opie" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/wcopie" }
    - { platform: bluesky,        user_url: "https://bsky.app/profile/op13.dev"}
    - { platform: x,              user_url: "https://x.com/OP13" }
  skin: dark

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      comments: true

comments:
  giscus:
    enabled: true
    repo: "william-opie/william-opie.github.io"
    repo_id: "R_kgDOKgrgZQ"
    category: "General"
    category_id: "DIC_kwDOKgrgZc4Ci5xw"
    mapping: "pathname"
    reactions_enabled: "1"
    theme: "dark"